# Generated by Django 4.1.6 on 2023-04-19 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_images', to='restaurant.image'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rate',
            field=models.IntegerField(blank=True, choices=[(5, '100'), (2, '40'), (4, '80'), (1, '20'), (3, '60')], null=True),
        ),
    ]
