# Generated by Django 4.1.6 on 2023-04-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_image_image_alter_restaurant_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='googleMapLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rate',
            field=models.IntegerField(blank=True, choices=[(1, '20'), (3, '60'), (4, '80'), (2, '40'), (5, '100')], null=True),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='close_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='day',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='open_at',
            field=models.CharField(max_length=20),
        ),
    ]
